a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('Contém letras?', a.isalpha())
print('É Alfanumérico?', a.isalnum())
print('Esta em letras maiusculas', a.isupper())
print('Esta em letras minisculas', a.islower())
print('Esta capitalizada?', a.istitle())
